name: MSBuild

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-2022
    steps:
      # Checkout git repository
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Add msbuild 
      # https://github.com/microsoft/setup-msbuild
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build app for release
        run: |
          msbuild -t:rebuild -verbosity:diag -property:Configuration=Release


