name: MSBuild

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout git repository
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup msbuild 
      # https://github.com/microsoft/setup-msbuild
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore the app
        run: |
          msbuild /t:Restore /p:Configuration=Release

      - name: Build app for release
        run: |
          msbuild /p:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: StarrySky
          path: ./src/StarrySky/bin/Release/StarrySky.pkgdef

              # Create the release:  https://github.com/actions/create-release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref}}
          release_name:  ${{ github.ref }}
          draft: false
          prerelease: false

